# Generated by Django 6.0.4 on 2026-04-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_number', models.CharField(blank=True, help_text='Deed number, if property is not yet in the registry', max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reports', to='properties.property')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queried_deed_number', models.CharField(help_text='Deed number the buyer typed in', max_length=50)),
                ('queried_owner_id', models.CharField(blank=True, help_text='Optional national ID the seller claims to have', max_length=20)),
                ('queried_address', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('UNKNOWN', 'Unknown / Not in Registry')], default='UNKNOWN', max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('authenticity_score', models.IntegerField(default=0)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('report_summary', models.TextField(blank=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='properties.property')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
