# Generated by Django 6.0.4 on 2026-04-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='related_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_number', models.CharField(db_index=True, help_text='Format e.g. 1234/2020 or DT 1234/2020', max_length=50, unique=True)),
                ('stand_number', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(default='Harare', max_length=100)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('size_sqm', models.DecimalField(decimal_places=2, help_text='Size in square metres', max_digits=10)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20)),
                ('registration_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed'), ('transferred', 'Transferred'), ('flagged', 'Flagged')], default='active', max_length=20)),
                ('market_value_estimate', models.DecimalField(decimal_places=2, help_text='Estimated value in USD', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
