# Generated by Django 6.0.4 on 2026-04-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_score', models.IntegerField(default=0, help_text='0–100')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', max_length=10)),
                ('status', models.CharField(choices=[('listed', 'Listed'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('flagged', 'Flagged for Fraud')], default='listed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('seller_id_mismatch', 'Seller is not the registered owner'), ('duplicate_active_listing', 'Property has another active listing'), ('recently_transferred', 'Property was recently transferred'), ('price_below_market', 'Listed price suspiciously below market value'), ('invalid_deed_number', 'Title deed number is invalid'), ('disputed_status', 'Property is currently disputed or flagged'), ('incomplete_record', 'Property record is incomplete'), ('multiple_listings_same_seller', 'Seller has unusually many recent listings'), ('unverified_owner', 'Registered owner identity is unverified')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('description', models.TextField()),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
    ]
